// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdpcldbrinzghstnfjga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcGNsZGJyaW56Z2hzdG5mamdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTYyOTQsImV4cCI6MjA2MTU5MjI5NH0.nqXqDF99dXaQW1Funas_P-M2R1qhG9tTCu2LZpFPWQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);